### ISSUE TITLE
Router middleware and swagger conflict

### ISSUE THREAD

**Issue by DaniloOliveira28** [davidffrench/Pacemaker#1]
Hello David,

I am studding the swagger + express application and your application was the first that I found that uses the express4 and swagger-node-express 2.0. Nice!

I am new in this subject, but I did not understand, why do use route if you already using the swagger-express to define your APIs?
You can access your router with or without /api/ path...

No?

Thanks!
Danilo

**Comment by davidffrench** [comment]
Hi Danilo,

You are correct. There is currently 2 express apis, the router listed under app and the one swagger uses. This shouldn't be the case, swagger should be the only one and the api should be accessed through this.

The reason i have both is for a few reasons. I created the routes without swagger in mind and added in swagger after the routes and logic were finished. I was short on time and didn't have time to modify the existing code to use swagger instead. This was my first node app and was a progressive learning experience. Express 4 was just released when i created the app and there was very little documentation out there that i could find about integrating it with swagger. If i find the time to refactor the code, i would change it to only use the routes through the swagger configuration.

Thank you very much for the comment and good luck with your application. I hope that my app can help and feel free to ask any other questions.

Regards,
David

**Comment by DaniloOliveira28** [comment]
Hello David,

Thank you for you feedback!
I am new with these tools too, I am learning a lot.

I think that I know the reason why your application is working with Expressjs 4. The routes middleware are from the version 4, so the routes api is worling version 4 and the swagger use the expressjs 3 compatibility mode (I think!).

One advantage of version expressjs 4 is that you can call the middlewares, between the event, like yours to check if the user is logged in. Summarising, you have a security problem, cause you need to be logged in by the APIs from routes, however if the guy discover your Swagger api, will be a party!

haha
bye
thanks!

**Comment by davidffrench** [comment]
Hi Danilo,

You are correct about the features not available for express through swagger. In hindsight, it would have been trivial to convert my routes to swagger had i used Express 3. Live and learn though.

I am aware of the security concern. I haven't fixed it because the app is just a dev side project and is not being used. 

Regards,
David
